ineterpo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from general.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", inicio, name="inicio"),
    path("noticias/", include("noticias.urls", namespace='noticias')),
    path("eventos/", eventos, name="eventos"),
    path("implementaciones/", implementaciones, name="implementaciones"),
    path("institucional/", institucional, name="institucional"),
    path("<str:modelo>/all", total_modelo, name="total_modelo"),
    path("<str:modelo>/<int:year>/<int:month>/<int:day>/<int:id>/", objeto_detalle, name="objeto_detalle"),
    path('tinymce/', include('tinymce.urls')),
]

# Solo servir archivos estáticos/media localmente en desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
    path('', views.noticias, name='noticias'),
    path('all/', views.total_noticias, name='total_noticias'),
    path('<int:year>/<int:month>/<int:day>/<int:id>/', views.noticia_detalle, name='noticia'),
]

templates/layout/header/components/HeaderNavSection.html
{% load static %}
<!-- Header Nav Section -->
<button id="menu-btn" class="lg:hidden z-30 text-white">
    <svg class="w-9 h-9" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
    </svg>

</button>
<nav id="nav-menu" class="flex-1 flex items-center justify-center transform translate-y-full opacity-0 bg-primary/90 backdrop-blur lg:bg-[#006400] overflow-hidden shadow-xl transition-all duration-200
    lg:transform-none lg:opacity-100 lg:block fixed lg:static bottom-0 top-0 h-full left-0 right-0 z-10">
    <ul class="flex flex-col lg:flex-row text-[16px] justify-between text-center items-center"> 
        <li class="relative flex-grow">
            <a href="{% url 'inicio' %}" class="nav-link" title="Hogar">
                <img class="w-6 mx-auto pb-1" src="{% static 'icons/header/home.svg' %}" alt="Logo de la pagina principal" width="24" height="24">
                    HOGAR
            </a>
        </li>
        <li class="relative flex-grow">
            <a href="{% url 'noticias:noticias' %}" class="nav-link" title="Noticias">
                <img class="w-6 mx-auto pb-1" src="{% static 'icons/header/notice.svg' %}" alt="Logo del apartado de Noticias" width="24" height="24">
                    NOTICIAS
            </a>
        </li>
        <li class="relative flex-grow">
            <a href="{% url 'eventos' %}" class="nav-link" title="Eventos">
                <img class="w-6 mx-auto pb-1" src="{% static 'icons/header/calendar.svg' %}" alt="Logo del apartado de Eventos" width="24" height="24">
                    EVENTOS
            </a>
        </li>
        <li class="relative flex-grow">
            <a href="{% url 'implementaciones' %}" class="nav-link" title="Implementaciones">
                <img class="w-6 mx-auto pb-1" src="{% static 'icons/header/implement.svg' %}" alt="Logo del apartado de Implementaciones" width="24" height="24">
                IMPLEMENTACIONES
            </a>
        </li>
        <li class="relative flex-grow">
            <a href="{% url 'institucional' %}" class="nav-link" title="Institucional">
                <img class="w-6 mx-auto pb-1" src="{% static 'icons/header/institute.svg' %}" alt="Logo del apartado de Institucional" width="24" height="24">
                INSTITUCIONAL
            </a>
        </li>
    </ul>
</nav>

templates/layout/header/components/HeaderTitleSection.html
{% load static %}
<!-- Header Title Section -->
<section class="flex items-center w-fit border-secundary gap-2 lg:gap-4 lg:ml-4 z-30">
    <div class="shadow-lg bg-white rounded-full p-2 md:p-2.5 aspect-square">
        <img class="aspect-square w-12 h-12 lg:w-14 lg:h-14 drop-shadow-[0_0_2px_rgba(0,0,0,0.15)]"
            src="{% static 'images/icoterpo.webp' %}" 
            alt="Logo del INETERPO" width="100" height="100" loading="lazy">
    </div>
    <h1 class="text-white font-source font-bold text-[2rem] leading-none border-secundary cursor-default border-l-2 pl-2 lg:text-4xl lg:pl-4"
        title="Institución Educativa Técnica Comercial Teófilo Roberto Potes">INETERPO</h1>
</section>